spring:
  mail:
    host : webcloud5.uk.syrahost.com
    username: contact@Suktha.com
    password: Suktha@2023$
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true